sudo: false
language: java
jdk:
- oraclejdk8
after_success:
- echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>"
  > ~/settings.xml
- if [ -z ${TRAVIS_TAG} ]; then mvn deploy --settings ~/settings.xml; fi
before_deploy:
- mvn package
- zip -r ${TRAVIS_TAG}.zip wisdom-orientdb-*/target/*.jar
deploy:
  provider: releases
  api_key:
    secure: VtxbEzV3HCMoYcRQNG3uGZO+gXYFsWvlo9ioYRxoFDaLNUqpvT4WUW7oPmh53/fhVQyFS959BPgvZq0dNbBMmO7Etox3IpmjgEiYtWuPz4z1gjhuRFr6m3o/r8AB4zLGXOv6KGuG+MgowfISdivXq/mIXjDheTgj2ConPMS7HME=
  file: ${TRAVIS_TAG}.zip
  on:
    tags: true
    all_branches: true
addons:
  coverity_scan:
    project:
      name: "wisdom-framework/wisdom-orientdb"
    notification_email: astrosus+orient@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: quality
